# Build settings
theme : minima
title: [Interactive visualizations for "Global reach, regional strength: Spatial patterns of a big science facility."]
description: [You can access the interactive and colored version of the maps for selected figures from the article below:]
